insert into Aliens values (1,'vikram','java');
insert into Aliens values (2,'Balaji','python');
insert into Aliens values (3,'ravi','java');
insert into Aliens values (4,'Bafs','java');
insert into Aliens values (8,'z','java');
insert into Aliens values (9,'a','java');
insert into Aliens values (103,'Balaji','python');
insert into Aliens values (22,'Balaji','python');
insert into Aliens values (25,'Balaji','python');
